In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(0,99,50)

array([ 0.        ,  2.02040816,  4.04081633,  6.06122449,  8.08163265,
       10.10204082, 12.12244898, 14.14285714, 16.16326531, 18.18367347,
       20.20408163, 22.2244898 , 24.24489796, 26.26530612, 28.28571429,
       30.30612245, 32.32653061, 34.34693878, 36.36734694, 38.3877551 ,
       40.40816327, 42.42857143, 44.44897959, 46.46938776, 48.48979592,
       50.51020408, 52.53061224, 54.55102041, 56.57142857, 58.59183673,
       60.6122449 , 62.63265306, 64.65306122, 66.67346939, 68.69387755,
       70.71428571, 72.73469388, 74.75510204, 76.7755102 , 78.79591837,
       80.81632653, 82.83673469, 84.85714286, 86.87755102, 88.89795918,
       90.91836735, 92.93877551, 94.95918367, 96.97959184, 99.        ])

In [28]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5)

array([0.21058831, 0.51876495, 0.50512513, 0.3614463 , 0.4999476 ])

In [30]:
np.random.rand(5,5)

array([[0.64907345, 0.8290842 , 0.414205  , 0.38576575, 0.30299569],
       [0.22541189, 0.9845729 , 0.84113775, 0.94010757, 0.12876681],
       [0.18313011, 0.70301013, 0.0031844 , 0.06828873, 0.48945998],
       [0.04533818, 0.36841569, 0.7727801 , 0.58266038, 0.668369  ],
       [0.32515956, 0.66290364, 0.61190224, 0.37667202, 0.48292828]])

In [31]:
np.random.randn(2)

array([-1.31869088,  0.05287051])

In [32]:
np.random.randn(4,4)

array([[ 0.97020741,  0.68430836,  0.49473718, -0.71232605],
       [ 1.13070636,  0.19118402,  0.32345959,  1.14143967],
       [ 0.19791695,  0.05118112, -0.99625901, -0.44212481],
       [-0.45139497, -0.5319461 , -0.1567157 ,  0.96476082]])

In [33]:
np.random.randint(1,101,10)

array([13, 32, 42,  6,  9, 21, 11, 49, 27, 28])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ran_arr = np.random.randint(0,50,10)

In [38]:
ran_arr

array([41,  4, 16, 29, 34,  0, 46, 23, 43, 11])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
ran_arr.max()

46

In [41]:
ran_arr.min()

0

In [42]:
ran_arr

array([41,  4, 16, 29, 34,  0, 46, 23, 43, 11])

The argmax and argmin methods give the position of the min and max values

In [43]:
ran_arr.argmax()

6

In [44]:
arr = arr.reshape(5,5)

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
arr.shape

(5, 5)

In [47]:
arr.dtype

dtype('int32')